/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as GuestChromeRouteImport } from './routes/_guest/_chrome'
import { Route as GuestWillkommenRouteImport } from './routes/_guest/willkommen'
import { Route as AdminShellRouteImport } from './routes/admin/_shell'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as GuestChromeAblaufRouteImport } from './routes/_guest/_chrome/ablauf'
import { Route as GuestChromeDatenschutzRouteImport } from './routes/_guest/_chrome/datenschutz'
import { Route as GuestChromeDresscodeRouteImport } from './routes/_guest/_chrome/dresscode'
import { Route as GuestChromeFaqRouteImport } from './routes/_guest/_chrome/faq'
import { Route as GuestChromeGeschenkeRouteImport } from './routes/_guest/_chrome/geschenke'
import { Route as GuestChromeKontaktRouteImport } from './routes/_guest/_chrome/kontakt'
import { Route as GuestChromeMehrRouteImport } from './routes/_guest/_chrome/mehr'
import { Route as GuestChromeStartRouteImport } from './routes/_guest/_chrome/start'
import { Route as GuestChromeZusagenRouteImport } from './routes/_guest/_chrome/zusagen'
import { Route as AdminShellIndexRouteImport } from './routes/admin/_shell/index'
import { Route as GuestChromeLocationIndexRouteImport } from './routes/_guest/_chrome/location/index'
import { Route as GuestChromeLocationFeierRouteImport } from './routes/_guest/_chrome/location/feier'
import { Route as GuestChromeLocationKircheRouteImport } from './routes/_guest/_chrome/location/kirche'
import { Route as AdminShellHaushalteIndexRouteImport } from './routes/admin/_shell/haushalte/index'
import { Route as AdminShellHaushalteHouseholdIdRouteImport } from './routes/admin/_shell/haushalte/$householdId'
import { Route as AdminShellHaushalteHouseholdIdRsvpRouteImport } from './routes/admin/_shell/haushalte/$householdId_.rsvp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestChromeRoute = GuestChromeRouteImport.update({
  id: '/_chrome',
  getParentRoute: () => GuestRoute,
} as any)
const GuestWillkommenRoute = GuestWillkommenRouteImport.update({
  id: '/willkommen',
  path: '/willkommen',
  getParentRoute: () => GuestRoute,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/admin/_shell',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestChromeAblaufRoute = GuestChromeAblaufRouteImport.update({
  id: '/ablauf',
  path: '/ablauf',
  getParentRoute: () => GuestChromeRoute,
} as any)
const GuestChromeDatenschutzRoute = GuestChromeDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => GuestChromeRoute,
} as any)
const GuestChromeDresscodeRoute = GuestChromeDresscodeRouteImport.update({
  id: '/dresscode',
  path: '/dresscode',
  getParentRoute: () => GuestChromeRoute,
} as any)
const GuestChromeFaqRoute = GuestChromeFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => GuestChromeRoute,
} as any)
const GuestChromeGeschenkeRoute = GuestChromeGeschenkeRouteImport.update({
  id: '/geschenke',
  path: '/geschenke',
  getParentRoute: () => GuestChromeRoute,
} as any)
const GuestChromeKontaktRoute = GuestChromeKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => GuestChromeRoute,
} as any)
const GuestChromeMehrRoute = GuestChromeMehrRouteImport.update({
  id: '/mehr',
  path: '/mehr',
  getParentRoute: () => GuestChromeRoute,
} as any)
const GuestChromeStartRoute = GuestChromeStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => GuestChromeRoute,
} as any)
const GuestChromeZusagenRoute = GuestChromeZusagenRouteImport.update({
  id: '/zusagen',
  path: '/zusagen',
  getParentRoute: () => GuestChromeRoute,
} as any)
const AdminShellIndexRoute = AdminShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShellRoute,
} as any)
const GuestChromeLocationIndexRoute =
  GuestChromeLocationIndexRouteImport.update({
    id: '/location/',
    path: '/location/',
    getParentRoute: () => GuestChromeRoute,
  } as any)
const GuestChromeLocationFeierRoute =
  GuestChromeLocationFeierRouteImport.update({
    id: '/location/feier',
    path: '/location/feier',
    getParentRoute: () => GuestChromeRoute,
  } as any)
const GuestChromeLocationKircheRoute =
  GuestChromeLocationKircheRouteImport.update({
    id: '/location/kirche',
    path: '/location/kirche',
    getParentRoute: () => GuestChromeRoute,
  } as any)
const AdminShellHaushalteIndexRoute =
  AdminShellHaushalteIndexRouteImport.update({
    id: '/haushalte/',
    path: '/haushalte/',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellHaushalteHouseholdIdRoute =
  AdminShellHaushalteHouseholdIdRouteImport.update({
    id: '/haushalte/$householdId',
    path: '/haushalte/$householdId',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellHaushalteHouseholdIdRsvpRoute =
  AdminShellHaushalteHouseholdIdRsvpRouteImport.update({
    id: '/haushalte/$householdId_/rsvp',
    path: '/haushalte/$householdId/rsvp',
    getParentRoute: () => AdminShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/willkommen': typeof GuestWillkommenRoute
  '/admin': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/ablauf': typeof GuestChromeAblaufRoute
  '/datenschutz': typeof GuestChromeDatenschutzRoute
  '/dresscode': typeof GuestChromeDresscodeRoute
  '/faq': typeof GuestChromeFaqRoute
  '/geschenke': typeof GuestChromeGeschenkeRoute
  '/kontakt': typeof GuestChromeKontaktRoute
  '/mehr': typeof GuestChromeMehrRoute
  '/start': typeof GuestChromeStartRoute
  '/zusagen': typeof GuestChromeZusagenRoute
  '/admin/': typeof AdminShellIndexRoute
  '/location/feier': typeof GuestChromeLocationFeierRoute
  '/location/kirche': typeof GuestChromeLocationKircheRoute
  '/admin/haushalte/$householdId': typeof AdminShellHaushalteHouseholdIdRoute
  '/location/': typeof GuestChromeLocationIndexRoute
  '/admin/haushalte/': typeof AdminShellHaushalteIndexRoute
  '/admin/haushalte/$householdId/rsvp': typeof AdminShellHaushalteHouseholdIdRsvpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/willkommen': typeof GuestWillkommenRoute
  '/admin/login': typeof AdminLoginRoute
  '/ablauf': typeof GuestChromeAblaufRoute
  '/datenschutz': typeof GuestChromeDatenschutzRoute
  '/dresscode': typeof GuestChromeDresscodeRoute
  '/faq': typeof GuestChromeFaqRoute
  '/geschenke': typeof GuestChromeGeschenkeRoute
  '/kontakt': typeof GuestChromeKontaktRoute
  '/mehr': typeof GuestChromeMehrRoute
  '/start': typeof GuestChromeStartRoute
  '/zusagen': typeof GuestChromeZusagenRoute
  '/admin': typeof AdminShellIndexRoute
  '/location/feier': typeof GuestChromeLocationFeierRoute
  '/location/kirche': typeof GuestChromeLocationKircheRoute
  '/admin/haushalte/$householdId': typeof AdminShellHaushalteHouseholdIdRoute
  '/location': typeof GuestChromeLocationIndexRoute
  '/admin/haushalte': typeof AdminShellHaushalteIndexRoute
  '/admin/haushalte/$householdId/rsvp': typeof AdminShellHaushalteHouseholdIdRsvpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_guest': typeof GuestRouteWithChildren
  '/_guest/_chrome': typeof GuestChromeRouteWithChildren
  '/_guest/willkommen': typeof GuestWillkommenRoute
  '/admin/_shell': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/_guest/_chrome/ablauf': typeof GuestChromeAblaufRoute
  '/_guest/_chrome/datenschutz': typeof GuestChromeDatenschutzRoute
  '/_guest/_chrome/dresscode': typeof GuestChromeDresscodeRoute
  '/_guest/_chrome/faq': typeof GuestChromeFaqRoute
  '/_guest/_chrome/geschenke': typeof GuestChromeGeschenkeRoute
  '/_guest/_chrome/kontakt': typeof GuestChromeKontaktRoute
  '/_guest/_chrome/mehr': typeof GuestChromeMehrRoute
  '/_guest/_chrome/start': typeof GuestChromeStartRoute
  '/_guest/_chrome/zusagen': typeof GuestChromeZusagenRoute
  '/admin/_shell/': typeof AdminShellIndexRoute
  '/_guest/_chrome/location/feier': typeof GuestChromeLocationFeierRoute
  '/_guest/_chrome/location/kirche': typeof GuestChromeLocationKircheRoute
  '/admin/_shell/haushalte/$householdId': typeof AdminShellHaushalteHouseholdIdRoute
  '/_guest/_chrome/location/': typeof GuestChromeLocationIndexRoute
  '/admin/_shell/haushalte/': typeof AdminShellHaushalteIndexRoute
  '/admin/_shell/haushalte/$householdId_/rsvp': typeof AdminShellHaushalteHouseholdIdRsvpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/willkommen'
    | '/admin'
    | '/admin/login'
    | '/ablauf'
    | '/datenschutz'
    | '/dresscode'
    | '/faq'
    | '/geschenke'
    | '/kontakt'
    | '/mehr'
    | '/start'
    | '/zusagen'
    | '/admin/'
    | '/location/feier'
    | '/location/kirche'
    | '/admin/haushalte/$householdId'
    | '/location/'
    | '/admin/haushalte/'
    | '/admin/haushalte/$householdId/rsvp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/willkommen'
    | '/admin/login'
    | '/ablauf'
    | '/datenschutz'
    | '/dresscode'
    | '/faq'
    | '/geschenke'
    | '/kontakt'
    | '/mehr'
    | '/start'
    | '/zusagen'
    | '/admin'
    | '/location/feier'
    | '/location/kirche'
    | '/admin/haushalte/$householdId'
    | '/location'
    | '/admin/haushalte'
    | '/admin/haushalte/$householdId/rsvp'
  id:
    | '__root__'
    | '/'
    | '/_guest'
    | '/_guest/_chrome'
    | '/_guest/willkommen'
    | '/admin/_shell'
    | '/admin/login'
    | '/_guest/_chrome/ablauf'
    | '/_guest/_chrome/datenschutz'
    | '/_guest/_chrome/dresscode'
    | '/_guest/_chrome/faq'
    | '/_guest/_chrome/geschenke'
    | '/_guest/_chrome/kontakt'
    | '/_guest/_chrome/mehr'
    | '/_guest/_chrome/start'
    | '/_guest/_chrome/zusagen'
    | '/admin/_shell/'
    | '/_guest/_chrome/location/feier'
    | '/_guest/_chrome/location/kirche'
    | '/admin/_shell/haushalte/$householdId'
    | '/_guest/_chrome/location/'
    | '/admin/_shell/haushalte/'
    | '/admin/_shell/haushalte/$householdId_/rsvp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuestRoute: typeof GuestRouteWithChildren
  AdminShellRoute: typeof AdminShellRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/_chrome': {
      id: '/_guest/_chrome'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestChromeRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/willkommen': {
      id: '/_guest/willkommen'
      path: '/willkommen'
      fullPath: '/willkommen'
      preLoaderRoute: typeof GuestWillkommenRouteImport
      parentRoute: typeof GuestRoute
    }
    '/admin/_shell': {
      id: '/admin/_shell'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/_chrome/ablauf': {
      id: '/_guest/_chrome/ablauf'
      path: '/ablauf'
      fullPath: '/ablauf'
      preLoaderRoute: typeof GuestChromeAblaufRouteImport
      parentRoute: typeof GuestChromeRoute
    }
    '/_guest/_chrome/datenschutz': {
      id: '/_guest/_chrome/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof GuestChromeDatenschutzRouteImport
      parentRoute: typeof GuestChromeRoute
    }
    '/_guest/_chrome/dresscode': {
      id: '/_guest/_chrome/dresscode'
      path: '/dresscode'
      fullPath: '/dresscode'
      preLoaderRoute: typeof GuestChromeDresscodeRouteImport
      parentRoute: typeof GuestChromeRoute
    }
    '/_guest/_chrome/faq': {
      id: '/_guest/_chrome/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof GuestChromeFaqRouteImport
      parentRoute: typeof GuestChromeRoute
    }
    '/_guest/_chrome/geschenke': {
      id: '/_guest/_chrome/geschenke'
      path: '/geschenke'
      fullPath: '/geschenke'
      preLoaderRoute: typeof GuestChromeGeschenkeRouteImport
      parentRoute: typeof GuestChromeRoute
    }
    '/_guest/_chrome/kontakt': {
      id: '/_guest/_chrome/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof GuestChromeKontaktRouteImport
      parentRoute: typeof GuestChromeRoute
    }
    '/_guest/_chrome/mehr': {
      id: '/_guest/_chrome/mehr'
      path: '/mehr'
      fullPath: '/mehr'
      preLoaderRoute: typeof GuestChromeMehrRouteImport
      parentRoute: typeof GuestChromeRoute
    }
    '/_guest/_chrome/start': {
      id: '/_guest/_chrome/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof GuestChromeStartRouteImport
      parentRoute: typeof GuestChromeRoute
    }
    '/_guest/_chrome/zusagen': {
      id: '/_guest/_chrome/zusagen'
      path: '/zusagen'
      fullPath: '/zusagen'
      preLoaderRoute: typeof GuestChromeZusagenRouteImport
      parentRoute: typeof GuestChromeRoute
    }
    '/admin/_shell/': {
      id: '/admin/_shell/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminShellIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/_guest/_chrome/location/': {
      id: '/_guest/_chrome/location/'
      path: '/location'
      fullPath: '/location/'
      preLoaderRoute: typeof GuestChromeLocationIndexRouteImport
      parentRoute: typeof GuestChromeRoute
    }
    '/_guest/_chrome/location/feier': {
      id: '/_guest/_chrome/location/feier'
      path: '/location/feier'
      fullPath: '/location/feier'
      preLoaderRoute: typeof GuestChromeLocationFeierRouteImport
      parentRoute: typeof GuestChromeRoute
    }
    '/_guest/_chrome/location/kirche': {
      id: '/_guest/_chrome/location/kirche'
      path: '/location/kirche'
      fullPath: '/location/kirche'
      preLoaderRoute: typeof GuestChromeLocationKircheRouteImport
      parentRoute: typeof GuestChromeRoute
    }
    '/admin/_shell/haushalte/': {
      id: '/admin/_shell/haushalte/'
      path: '/haushalte'
      fullPath: '/admin/haushalte/'
      preLoaderRoute: typeof AdminShellHaushalteIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/haushalte/$householdId': {
      id: '/admin/_shell/haushalte/$householdId'
      path: '/haushalte/$householdId'
      fullPath: '/admin/haushalte/$householdId'
      preLoaderRoute: typeof AdminShellHaushalteHouseholdIdRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/haushalte/$householdId_/rsvp': {
      id: '/admin/_shell/haushalte/$householdId_/rsvp'
      path: '/haushalte/$householdId/rsvp'
      fullPath: '/admin/haushalte/$householdId/rsvp'
      preLoaderRoute: typeof AdminShellHaushalteHouseholdIdRsvpRouteImport
      parentRoute: typeof AdminShellRoute
    }
  }
}

interface GuestChromeRouteChildren {
  GuestChromeAblaufRoute: typeof GuestChromeAblaufRoute
  GuestChromeDatenschutzRoute: typeof GuestChromeDatenschutzRoute
  GuestChromeDresscodeRoute: typeof GuestChromeDresscodeRoute
  GuestChromeFaqRoute: typeof GuestChromeFaqRoute
  GuestChromeGeschenkeRoute: typeof GuestChromeGeschenkeRoute
  GuestChromeKontaktRoute: typeof GuestChromeKontaktRoute
  GuestChromeMehrRoute: typeof GuestChromeMehrRoute
  GuestChromeStartRoute: typeof GuestChromeStartRoute
  GuestChromeZusagenRoute: typeof GuestChromeZusagenRoute
  GuestChromeLocationFeierRoute: typeof GuestChromeLocationFeierRoute
  GuestChromeLocationKircheRoute: typeof GuestChromeLocationKircheRoute
  GuestChromeLocationIndexRoute: typeof GuestChromeLocationIndexRoute
}

const GuestChromeRouteChildren: GuestChromeRouteChildren = {
  GuestChromeAblaufRoute: GuestChromeAblaufRoute,
  GuestChromeDatenschutzRoute: GuestChromeDatenschutzRoute,
  GuestChromeDresscodeRoute: GuestChromeDresscodeRoute,
  GuestChromeFaqRoute: GuestChromeFaqRoute,
  GuestChromeGeschenkeRoute: GuestChromeGeschenkeRoute,
  GuestChromeKontaktRoute: GuestChromeKontaktRoute,
  GuestChromeMehrRoute: GuestChromeMehrRoute,
  GuestChromeStartRoute: GuestChromeStartRoute,
  GuestChromeZusagenRoute: GuestChromeZusagenRoute,
  GuestChromeLocationFeierRoute: GuestChromeLocationFeierRoute,
  GuestChromeLocationKircheRoute: GuestChromeLocationKircheRoute,
  GuestChromeLocationIndexRoute: GuestChromeLocationIndexRoute,
}

const GuestChromeRouteWithChildren = GuestChromeRoute._addFileChildren(
  GuestChromeRouteChildren,
)

interface GuestRouteChildren {
  GuestChromeRoute: typeof GuestChromeRouteWithChildren
  GuestWillkommenRoute: typeof GuestWillkommenRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestChromeRoute: GuestChromeRouteWithChildren,
  GuestWillkommenRoute: GuestWillkommenRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface AdminShellRouteChildren {
  AdminShellIndexRoute: typeof AdminShellIndexRoute
  AdminShellHaushalteHouseholdIdRoute: typeof AdminShellHaushalteHouseholdIdRoute
  AdminShellHaushalteIndexRoute: typeof AdminShellHaushalteIndexRoute
  AdminShellHaushalteHouseholdIdRsvpRoute: typeof AdminShellHaushalteHouseholdIdRsvpRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellIndexRoute: AdminShellIndexRoute,
  AdminShellHaushalteHouseholdIdRoute: AdminShellHaushalteHouseholdIdRoute,
  AdminShellHaushalteIndexRoute: AdminShellHaushalteIndexRoute,
  AdminShellHaushalteHouseholdIdRsvpRoute:
    AdminShellHaushalteHouseholdIdRsvpRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuestRoute: GuestRouteWithChildren,
  AdminShellRoute: AdminShellRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
