/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as GuestStartRouteImport } from './routes/_guest/start'
import { Route as GuestWillkommenRouteImport } from './routes/_guest/willkommen'
import { Route as GuestZusagenRouteImport } from './routes/_guest/zusagen'
import { Route as AdminShellRouteImport } from './routes/admin/_shell'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminShellIndexRouteImport } from './routes/admin/_shell/index'
import { Route as AdminShellHaushalteIndexRouteImport } from './routes/admin/_shell/haushalte/index'
import { Route as AdminShellHaushalteHouseholdIdRouteImport } from './routes/admin/_shell/haushalte/$householdId'
import { Route as AdminShellHaushalteHouseholdIdRsvpRouteImport } from './routes/admin/_shell/haushalte/$householdId_.rsvp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestStartRoute = GuestStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => GuestRoute,
} as any)
const GuestWillkommenRoute = GuestWillkommenRouteImport.update({
  id: '/willkommen',
  path: '/willkommen',
  getParentRoute: () => GuestRoute,
} as any)
const GuestZusagenRoute = GuestZusagenRouteImport.update({
  id: '/zusagen',
  path: '/zusagen',
  getParentRoute: () => GuestRoute,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/admin/_shell',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellIndexRoute = AdminShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellHaushalteIndexRoute =
  AdminShellHaushalteIndexRouteImport.update({
    id: '/haushalte/',
    path: '/haushalte/',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellHaushalteHouseholdIdRoute =
  AdminShellHaushalteHouseholdIdRouteImport.update({
    id: '/haushalte/$householdId',
    path: '/haushalte/$householdId',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellHaushalteHouseholdIdRsvpRoute =
  AdminShellHaushalteHouseholdIdRsvpRouteImport.update({
    id: '/haushalte/$householdId_/rsvp',
    path: '/haushalte/$householdId/rsvp',
    getParentRoute: () => AdminShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/start': typeof GuestStartRoute
  '/willkommen': typeof GuestWillkommenRoute
  '/zusagen': typeof GuestZusagenRoute
  '/admin': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminShellIndexRoute
  '/admin/haushalte/$householdId': typeof AdminShellHaushalteHouseholdIdRoute
  '/admin/haushalte/': typeof AdminShellHaushalteIndexRoute
  '/admin/haushalte/$householdId/rsvp': typeof AdminShellHaushalteHouseholdIdRsvpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/start': typeof GuestStartRoute
  '/willkommen': typeof GuestWillkommenRoute
  '/zusagen': typeof GuestZusagenRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminShellIndexRoute
  '/admin/haushalte/$householdId': typeof AdminShellHaushalteHouseholdIdRoute
  '/admin/haushalte': typeof AdminShellHaushalteIndexRoute
  '/admin/haushalte/$householdId/rsvp': typeof AdminShellHaushalteHouseholdIdRsvpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_guest': typeof GuestRouteWithChildren
  '/_guest/start': typeof GuestStartRoute
  '/_guest/willkommen': typeof GuestWillkommenRoute
  '/_guest/zusagen': typeof GuestZusagenRoute
  '/admin/_shell': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_shell/': typeof AdminShellIndexRoute
  '/admin/_shell/haushalte/$householdId': typeof AdminShellHaushalteHouseholdIdRoute
  '/admin/_shell/haushalte/': typeof AdminShellHaushalteIndexRoute
  '/admin/_shell/haushalte/$householdId_/rsvp': typeof AdminShellHaushalteHouseholdIdRsvpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/start'
    | '/willkommen'
    | '/zusagen'
    | '/admin'
    | '/admin/login'
    | '/admin/'
    | '/admin/haushalte/$householdId'
    | '/admin/haushalte/'
    | '/admin/haushalte/$householdId/rsvp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/start'
    | '/willkommen'
    | '/zusagen'
    | '/admin/login'
    | '/admin'
    | '/admin/haushalte/$householdId'
    | '/admin/haushalte'
    | '/admin/haushalte/$householdId/rsvp'
  id:
    | '__root__'
    | '/'
    | '/_guest'
    | '/_guest/start'
    | '/_guest/willkommen'
    | '/_guest/zusagen'
    | '/admin/_shell'
    | '/admin/login'
    | '/admin/_shell/'
    | '/admin/_shell/haushalte/$householdId'
    | '/admin/_shell/haushalte/'
    | '/admin/_shell/haushalte/$householdId_/rsvp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuestRoute: typeof GuestRouteWithChildren
  AdminShellRoute: typeof AdminShellRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/start': {
      id: '/_guest/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof GuestStartRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/willkommen': {
      id: '/_guest/willkommen'
      path: '/willkommen'
      fullPath: '/willkommen'
      preLoaderRoute: typeof GuestWillkommenRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/zusagen': {
      id: '/_guest/zusagen'
      path: '/zusagen'
      fullPath: '/zusagen'
      preLoaderRoute: typeof GuestZusagenRouteImport
      parentRoute: typeof GuestRoute
    }
    '/admin/_shell': {
      id: '/admin/_shell'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell/': {
      id: '/admin/_shell/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminShellIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/haushalte/': {
      id: '/admin/_shell/haushalte/'
      path: '/haushalte'
      fullPath: '/admin/haushalte/'
      preLoaderRoute: typeof AdminShellHaushalteIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/haushalte/$householdId': {
      id: '/admin/_shell/haushalte/$householdId'
      path: '/haushalte/$householdId'
      fullPath: '/admin/haushalte/$householdId'
      preLoaderRoute: typeof AdminShellHaushalteHouseholdIdRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/haushalte/$householdId_/rsvp': {
      id: '/admin/_shell/haushalte/$householdId_/rsvp'
      path: '/haushalte/$householdId/rsvp'
      fullPath: '/admin/haushalte/$householdId/rsvp'
      preLoaderRoute: typeof AdminShellHaushalteHouseholdIdRsvpRouteImport
      parentRoute: typeof AdminShellRoute
    }
  }
}

interface GuestRouteChildren {
  GuestStartRoute: typeof GuestStartRoute
  GuestWillkommenRoute: typeof GuestWillkommenRoute
  GuestZusagenRoute: typeof GuestZusagenRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestStartRoute: GuestStartRoute,
  GuestWillkommenRoute: GuestWillkommenRoute,
  GuestZusagenRoute: GuestZusagenRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface AdminShellRouteChildren {
  AdminShellIndexRoute: typeof AdminShellIndexRoute
  AdminShellHaushalteHouseholdIdRoute: typeof AdminShellHaushalteHouseholdIdRoute
  AdminShellHaushalteIndexRoute: typeof AdminShellHaushalteIndexRoute
  AdminShellHaushalteHouseholdIdRsvpRoute: typeof AdminShellHaushalteHouseholdIdRsvpRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellIndexRoute: AdminShellIndexRoute,
  AdminShellHaushalteHouseholdIdRoute: AdminShellHaushalteHouseholdIdRoute,
  AdminShellHaushalteIndexRoute: AdminShellHaushalteIndexRoute,
  AdminShellHaushalteHouseholdIdRsvpRoute:
    AdminShellHaushalteHouseholdIdRsvpRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuestRoute: GuestRouteWithChildren,
  AdminShellRoute: AdminShellRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
